export type RegionalCategory = 'All' | 'Americas' | 'Europe' | 'Asia-Pacific' | 'Global';

export interface RegionalOption {
  id: string;
  value: string;
  label: string;
  subLabel: string;
  nativeName?: string;
  region: RegionalCategory;
  flag: string;
  symbol?: string;
  badge?: string;
  badgeColor?: string;
  samplePrice?: string;
  sampleDate?: string;
}

export const DEFAULT_CURRENCY_OPTIONS: RegionalOption[] = [
  {
    id: 'usd',
    value: 'USD ($)',
    label: 'USD ($)',
    subLabel: 'United States Dollar',
    region: 'Americas',
    flag: '🇺🇸',
    symbol: '$',
    badge: 'Default',
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    samplePrice: '$49.95 USD',
  },
  {
    id: 'cad',
    value: 'CAD ($)',
    label: 'CAD ($)',
    subLabel: 'Canadian Dollar',
    region: 'Americas',
    flag: '🇨🇦',
    symbol: 'CA$',
    badge: 'Popular',
    samplePrice: 'CA$67.50 CAD',
  },
  {
    id: 'eur',
    value: 'EUR (€)',
    label: 'EUR (€)',
    subLabel: 'Euro (European Union)',
    region: 'Europe',
    flag: '🇪🇺',
    symbol: '€',
    badge: 'Popular',
    samplePrice: '€45.90 EUR',
  },
  {
    id: 'gbp',
    value: 'GBP (£)',
    label: 'GBP (£)',
    subLabel: 'British Pound Sterling',
    region: 'Europe',
    flag: '🇬🇧',
    symbol: '£',
    badge: 'Popular',
    samplePrice: '£39.95 GBP',
  },
  {
    id: 'aud',
    value: 'AUD ($)',
    label: 'AUD ($)',
    subLabel: 'Australian Dollar',
    region: 'Asia-Pacific',
    flag: '🇦🇺',
    symbol: 'A$',
    badge: 'Popular',
    samplePrice: 'A$74.20 AUD',
  },
  {
    id: 'jpy',
    value: 'JPY (¥)',
    label: 'JPY (¥)',
    subLabel: 'Japanese Yen',
    region: 'Asia-Pacific',
    flag: '🇯🇵',
    symbol: '¥',
    badge: 'Major',
    samplePrice: '¥7,500 JPY',
  },
  {
    id: 'chf',
    value: 'CHF (Fr)',
    label: 'CHF (Fr)',
    subLabel: 'Swiss Franc',
    region: 'Europe',
    flag: '🇨🇭',
    symbol: 'CHF',
    badge: 'Global',
    samplePrice: '44.50 CHF',
  },
  {
    id: 'nzd',
    value: 'NZD ($)',
    label: 'NZD ($)',
    subLabel: 'New Zealand Dollar',
    region: 'Asia-Pacific',
    flag: '🇳🇿',
    symbol: 'NZ$',
    badge: 'Global',
    samplePrice: 'NZ$82.10 NZD',
  },
  {
    id: 'sgd',
    value: 'SGD ($)',
    label: 'SGD ($)',
    subLabel: 'Singapore Dollar',
    region: 'Asia-Pacific',
    flag: '🇸🇬',
    symbol: 'S$',
    badge: 'Global',
    samplePrice: 'S$65.80 SGD',
  },
];

export const DEFAULT_LANGUAGE_OPTIONS: RegionalOption[] = [
  {
    id: 'en-us',
    value: 'English (US)',
    label: 'English (US)',
    subLabel: 'English (United States)',
    nativeName: 'English',
    region: 'Americas',
    flag: '🇺🇸',
    badge: 'Primary',
    badgeColor: 'bg-[#fff1f2] text-[#D30915] border-[#fecdd3]',
    sampleDate: 'Friday, September 4, 2026',
  },
  {
    id: 'en-uk',
    value: 'English (UK)',
    label: 'English (UK)',
    subLabel: 'English (United Kingdom & Commonwealth)',
    nativeName: 'English (UK)',
    region: 'Europe',
    flag: '🇬🇧',
    badge: 'Popular',
    sampleDate: 'Friday, 4 September 2026',
  },
  {
    id: 'es',
    value: 'Español',
    label: 'Español',
    subLabel: 'Spanish (Spain & Latin America)',
    nativeName: 'Español',
    region: 'Americas',
    flag: '🇪🇸',
    badge: 'Popular',
    sampleDate: 'Viernes, 4 de septiembre de 2026',
  },
  {
    id: 'fr',
    value: 'Français',
    label: 'Français',
    subLabel: 'French (France & Canada)',
    nativeName: 'Français',
    region: 'Europe',
    flag: '🇫🇷',
    badge: 'Global',
    sampleDate: 'Vendredi 4 septembre 2026',
  },
  {
    id: 'de',
    value: 'Deutsch',
    label: 'Deutsch',
    subLabel: 'German (Germany, Austria, Switzerland)',
    nativeName: 'Deutsch',
    region: 'Europe',
    flag: '🇩🇪',
    badge: 'EU',
    sampleDate: 'Freitag, 4. September 2026',
  },
  {
    id: 'it',
    value: 'Italiano',
    label: 'Italiano',
    subLabel: 'Italian (Italy & Switzerland)',
    nativeName: 'Italiano',
    region: 'Europe',
    flag: '🇮🇹',
    badge: 'EU',
    sampleDate: 'Venerdì 4 settembre 2026',
  },
  {
    id: 'pt',
    value: 'Português',
    label: 'Português',
    subLabel: 'Portuguese (Brazil & Portugal)',
    nativeName: 'Português',
    region: 'Americas',
    flag: '🇧🇷',
    badge: 'Global',
    sampleDate: 'Sexta-feira, 4 de setembro de 2026',
  },
  {
    id: 'nl',
    value: 'Nederlands',
    label: 'Nederlands',
    subLabel: 'Dutch (Netherlands & Belgium)',
    nativeName: 'Nederlands',
    region: 'Europe',
    flag: '🇳🇱',
    badge: 'EU',
    sampleDate: 'Vrijdag 4 september 2026',
  },
  {
    id: 'ja',
    value: '日本語',
    label: '日本語',
    subLabel: 'Japanese (Japan)',
    nativeName: '日本語',
    region: 'Asia-Pacific',
    flag: '🇯🇵',
    badge: 'Asia',
    sampleDate: '2026年9月4日 金曜日',
  },
];
