-- ====================================================================
-- ILOVESURPRISES PHASE 6: PRODUCTION CATALOG REPLACEMENT (SAFE CUTOVER)
-- Target Database: grwhdtvorhdvyvcxwomn (Supabase)
-- 
-- STRICT SAFETY GUARANTEES:
-- 1. ZERO USE OF 'CASCADE'. No cascade paths can touch any external table.
-- 2. Strictly non-destructive to ALL protected business & auth data:
--    auth.users, profiles, orders, order_items, commissions, payouts,
--    reviews, representatives, and Firebase customer-auth data.
-- 3. Explicit child-to-parent DELETE order: only the 9 catalog tables cleared.
-- 4. Explicit parent-to-child INSERT with 100% named column lists.
-- 5. Atomic transaction block (BEGIN ... COMMIT) ensures total rollback on error.
-- ====================================================================

-- STEP 1: Ensure Production Tables Exist (bigint-safe for inventory)
CREATE TABLE IF NOT EXISTS public.products (
  product_id text PRIMARY KEY,
  handle text UNIQUE NOT NULL,
  title text NOT NULL,
  body_html text,
  vendor text,
  product_type text,
  tags text,
  created_at timestamptz,
  updated_at timestamptz,
  status text,
  published boolean,
  published_at timestamptz,
  template_suffix text,
  gift_card boolean,
  source_url text,
  total_inventory_qty bigint,
  category_id text,
  category_name text,
  seo_title text,
  seo_description text
);

CREATE TABLE IF NOT EXISTS public.product_variants (
  variant_id text PRIMARY KEY,
  product_id text NOT NULL REFERENCES public.products(product_id),
  position integer,
  sku text,
  barcode text,
  option1_name text,
  option1_value text,
  option2_name text,
  option2_value text,
  option3_name text,
  option3_value text,
  image_url text,
  weight numeric,
  weight_unit text,
  price numeric,
  compare_at_price numeric,
  taxable boolean,
  inventory_item_id text,
  inventory_tracker text,
  inventory_policy text,
  fulfillment_service text,
  requires_shipping boolean,
  shipping_profile text,
  inventory_qty integer,
  cost numeric,
  hs_code text,
  country_of_origin text,
  province_of_origin text
);

CREATE TABLE IF NOT EXISTS public.product_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL REFERENCES public.products(product_id),
  image_url text NOT NULL,
  image_type text,
  position integer,
  width integer,
  height integer,
  alt_text text
);

CREATE TABLE IF NOT EXISTS public.product_options (
  option_key text PRIMARY KEY,
  product_id text NOT NULL REFERENCES public.products(product_id),
  position integer NOT NULL,
  source_name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_option_values (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  option_key text NOT NULL REFERENCES public.product_options(option_key),
  product_id text NOT NULL REFERENCES public.products(product_id),
  value text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.collections (
  collection_id text PRIMARY KEY,
  handle text UNIQUE NOT NULL,
  title text NOT NULL,
  body_html text,
  sort_order text,
  template_suffix text,
  updated_at timestamptz,
  image_url text,
  products_count integer,
  published_online_store boolean,
  source_type text,
  inclusion_type text,
  inclusion_match text,
  seo_title text,
  seo_description text,
  smartseo_meta_title text,
  smartseo_meta_description text,
  smartseo_meta_keywords text
);

CREATE TABLE IF NOT EXISTS public.product_collections (
  collection_id text NOT NULL REFERENCES public.collections(collection_id),
  product_id text NOT NULL REFERENCES public.products(product_id),
  collection_handle text,
  product_handle text,
  sort_position integer,
  source_verified text,
  PRIMARY KEY (collection_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.collection_conditions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES public.collections(collection_id),
  condition_no integer,
  field text,
  relation text,
  value text,
  match text
);

CREATE TABLE IF NOT EXISTS public.collection_metafields (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES public.collections(collection_id),
  namespace_key text NOT NULL,
  metafield_type text,
  value text
);

CREATE TABLE IF NOT EXISTS public.product_metafields (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL REFERENCES public.products(product_id),
  namespace_key text NOT NULL,
  metafield_type text,
  value text
);

CREATE TABLE IF NOT EXISTS public.variant_metafields (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id text NOT NULL REFERENCES public.product_variants(variant_id),
  namespace_key text NOT NULL,
  metafield_type text,
  value text
);

-- Ensure column type is bigint if previously created as integer
ALTER TABLE public.products ALTER COLUMN total_inventory_qty TYPE bigint;

-- STEP 2: Atomic Transaction for Safe Data Replacement (NO CASCADE)
BEGIN;

-- 2A. Explicit Child-to-Parent Deletion (Guarantees zero impact on non-catalog tables)
DELETE FROM public.collection_metafields;
DELETE FROM public.collection_conditions;
DELETE FROM public.product_collections;
DELETE FROM public.product_option_values;
DELETE FROM public.product_options;
DELETE FROM public.product_images;
DELETE FROM public.variant_metafields;
DELETE FROM public.product_metafields;
DELETE FROM public.product_variants;
DELETE FROM public.products;
DELETE FROM public.collections;

-- 2B. Parent-to-Child Insertion with 100% Named Columns
INSERT INTO public.collections (
  collection_id, handle, title, body_html, sort_order, template_suffix,
  updated_at, image_url, products_count, published_online_store, source_type,
  inclusion_type, inclusion_match, seo_title, seo_description,
  smartseo_meta_title, smartseo_meta_description, smartseo_meta_keywords
)
SELECT 
  collection_id, handle, title, body_html, sort_order, template_suffix,
  updated_at, image_url, products_count, published_online_store, source_type,
  inclusion_type, inclusion_match, seo_title, seo_description,
  smartseo_meta_title, smartseo_meta_description, smartseo_meta_keywords
FROM public.staging_collections;

INSERT INTO public.products (
  product_id, handle, title, body_html, vendor, product_type, tags,
  created_at, updated_at, status, published, published_at, template_suffix,
  gift_card, source_url, total_inventory_qty, category_id, category_name,
  seo_title, seo_description
)
SELECT 
  product_id, handle, title, body_html, vendor, product_type, tags,
  created_at, updated_at, status, published, published_at, template_suffix,
  gift_card, source_url, total_inventory_qty, category_id, category_name,
  seo_title, seo_description
FROM public.staging_products;

INSERT INTO public.product_variants (
  variant_id, product_id, position, sku, barcode, option1_name, option1_value,
  option2_name, option2_value, option3_name, option3_value, image_url, weight,
  weight_unit, price, compare_at_price, taxable, inventory_item_id,
  inventory_tracker, inventory_policy, fulfillment_service, requires_shipping,
  shipping_profile, inventory_qty, cost, hs_code, country_of_origin, province_of_origin
)
SELECT 
  variant_id, product_id, position, sku, barcode, option1_name, option1_value,
  option2_name, option2_value, option3_name, option3_value, image_url, weight,
  weight_unit, price, compare_at_price, taxable, inventory_item_id,
  inventory_tracker, inventory_policy, fulfillment_service, requires_shipping,
  shipping_profile, inventory_qty, cost, hs_code, country_of_origin, province_of_origin
FROM public.staging_product_variants;

INSERT INTO public.product_images (
  id, product_id, image_url, image_type, position, width, height, alt_text
)
SELECT 
  id, product_id, image_url, image_type, position, width, height, alt_text
FROM public.staging_product_images;

INSERT INTO public.product_options (
  option_key, product_id, position, source_name
)
SELECT 
  option_key, product_id, position, source_name
FROM public.staging_product_options;

INSERT INTO public.product_option_values (
  id, option_key, product_id, value
)
SELECT 
  id, option_key, product_id, value
FROM public.staging_product_option_values;

INSERT INTO public.product_collections (
  collection_id, product_id, collection_handle, product_handle,
  sort_position, source_verified
)
SELECT 
  collection_id, product_id, collection_handle, product_handle,
  sort_position, source_verified
FROM public.staging_product_collections;

INSERT INTO public.collection_conditions (
  id, collection_id, condition_no, field, relation, value, match
)
SELECT 
  id, collection_id, condition_no, field, relation, value, match
FROM public.staging_collection_conditions;

INSERT INTO public.collection_metafields (
  id, collection_id, namespace_key, metafield_type, value
)
SELECT 
  id, collection_id, namespace_key, metafield_type, value
FROM public.staging_collection_metafields;

INSERT INTO public.product_metafields (
  id, product_id, namespace_key, metafield_type, value
)
SELECT 
  id, product_id, namespace_key, metafield_type, value
FROM public.staging_product_metafields;

INSERT INTO public.variant_metafields (
  id, variant_id, namespace_key, metafield_type, value
)
SELECT 
  id, variant_id, namespace_key, metafield_type, value
FROM public.staging_variant_metafields;

COMMIT;

-- STEP 3: High-Performance B-Tree Indexes
CREATE INDEX IF NOT EXISTS idx_prod_variants_product ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_prod_images_product ON public.product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_prod_pc_product ON public.product_collections(product_id);
CREATE INDEX IF NOT EXISTS idx_prod_pc_collection ON public.product_collections(collection_id);
CREATE INDEX IF NOT EXISTS idx_prod_products_handle ON public.products(handle);
CREATE INDEX IF NOT EXISTS idx_prod_collections_handle ON public.collections(handle);

-- STEP 4: Row Level Security & Public Read Policies
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_option_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_conditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_metafields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_metafields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.variant_metafields ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read on products" ON public.products;
CREATE POLICY "Allow public read on products" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_variants" ON public.product_variants;
CREATE POLICY "Allow public read on product_variants" ON public.product_variants FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_images" ON public.product_images;
CREATE POLICY "Allow public read on product_images" ON public.product_images FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_options" ON public.product_options;
CREATE POLICY "Allow public read on product_options" ON public.product_options FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_option_values" ON public.product_option_values;
CREATE POLICY "Allow public read on product_option_values" ON public.product_option_values FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on collections" ON public.collections;
CREATE POLICY "Allow public read on collections" ON public.collections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_collections" ON public.product_collections;
CREATE POLICY "Allow public read on product_collections" ON public.product_collections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on collection_conditions" ON public.collection_conditions;
CREATE POLICY "Allow public read on collection_conditions" ON public.collection_conditions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on collection_metafields" ON public.collection_metafields;
CREATE POLICY "Allow public read on collection_metafields" ON public.collection_metafields FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_metafields" ON public.product_metafields;
CREATE POLICY "Allow public read on product_metafields" ON public.product_metafields FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on variant_metafields" ON public.variant_metafields;
CREATE POLICY "Allow public read on variant_metafields" ON public.variant_metafields FOR SELECT USING (true);

GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated;

-- STEP 5: Verification Output
SELECT 'products' AS table_name, count(*) AS row_count FROM public.products
UNION ALL
SELECT 'product_variants', count(*) FROM public.product_variants
UNION ALL
SELECT 'product_images', count(*) FROM public.product_images
UNION ALL
SELECT 'collections', count(*) FROM public.collections
UNION ALL
SELECT 'product_collections', count(*) FROM public.product_collections
UNION ALL
SELECT 'product_options', count(*) FROM public.product_options
UNION ALL
SELECT 'product_option_values', count(*) FROM public.product_option_values
UNION ALL
SELECT 'collection_conditions', count(*) FROM public.collection_conditions
UNION ALL
SELECT 'collection_metafields', count(*) FROM public.collection_metafields
UNION ALL
SELECT 'product_metafields', count(*) FROM public.product_metafields
UNION ALL
SELECT 'variant_metafields', count(*) FROM public.variant_metafields;
