-- ====================================================================
-- ILOVESURPRISES PHASE 6: PRODUCTION CATALOG REPLACEMENT SCRIPT
-- Target Database: grwhdtvorhdvyvcxwomn (Supabase)
-- 
-- CRITICAL SAFETY GUARANTEES:
-- - ONLY touches catalog tables: products, product_variants, product_images,
--   product_options, product_option_values, collections, product_collections,
--   collection_conditions, collection_metafields.
-- - ZERO MODIFICATIONS to auth.users, profiles, orders, order_items,
--   commissions, payouts, reviews, representatives, or Firebase customer auth.
-- - Copies directly from 100% verified staging tables.
-- - Atomic transaction safety: all inserts protected by BEGIN ... COMMIT.
-- ====================================================================

-- 1. Create Production Catalog Tables (Bigint safe for 10.89B inventory)
CREATE TABLE IF NOT EXISTS public.products (
  product_id text PRIMARY KEY,
  handle text UNIQUE NOT NULL,
  title text NOT NULL,
  body_html text,
  vendor text,
  product_type text,
  tags text,
  created_at timestamptz,
  updated_at timestamptz,
  status text,
  published boolean,
  published_at timestamptz,
  template_suffix text,
  gift_card boolean,
  source_url text,
  total_inventory_qty bigint,
  category_id text,
  category_name text,
  seo_title text,
  seo_description text
);

CREATE TABLE IF NOT EXISTS public.product_variants (
  variant_id text PRIMARY KEY,
  product_id text NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  position integer,
  sku text,
  barcode text,
  option1_name text,
  option1_value text,
  option2_name text,
  option2_value text,
  option3_name text,
  option3_value text,
  image_url text,
  weight numeric,
  weight_unit text,
  price numeric,
  compare_at_price numeric,
  taxable boolean,
  inventory_item_id text,
  inventory_tracker text,
  inventory_policy text,
  fulfillment_service text,
  requires_shipping boolean,
  shipping_profile text,
  inventory_qty integer,
  cost numeric,
  hs_code text,
  country_of_origin text,
  province_of_origin text
);

CREATE TABLE IF NOT EXISTS public.product_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  image_url text NOT NULL,
  image_type text,
  position integer,
  width integer,
  height integer,
  alt_text text
);

CREATE TABLE IF NOT EXISTS public.product_options (
  option_key text PRIMARY KEY,
  product_id text NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  position integer NOT NULL,
  source_name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_option_values (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  option_key text NOT NULL REFERENCES public.product_options(option_key) ON DELETE CASCADE,
  product_id text NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  value text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.collections (
  collection_id text PRIMARY KEY,
  handle text UNIQUE NOT NULL,
  title text NOT NULL,
  body_html text,
  sort_order text,
  template_suffix text,
  updated_at timestamptz,
  image_url text,
  products_count integer,
  published_online_store boolean,
  source_type text,
  inclusion_type text,
  inclusion_match text,
  seo_title text,
  seo_description text,
  smartseo_meta_title text,
  smartseo_meta_description text,
  smartseo_meta_keywords text
);

CREATE TABLE IF NOT EXISTS public.product_collections (
  collection_id text NOT NULL REFERENCES public.collections(collection_id) ON DELETE CASCADE,
  product_id text NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  collection_handle text,
  product_handle text,
  sort_position integer,
  source_verified text,
  PRIMARY KEY (collection_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.collection_conditions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES public.collections(collection_id) ON DELETE CASCADE,
  condition_no integer,
  field text,
  relation text,
  value text,
  match text
);

CREATE TABLE IF NOT EXISTS public.collection_metafields (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES public.collections(collection_id) ON DELETE CASCADE,
  namespace_key text NOT NULL,
  metafield_type text,
  value text
);

CREATE TABLE IF NOT EXISTS public.product_metafields (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  namespace_key text NOT NULL,
  metafield_type text,
  value text
);

CREATE TABLE IF NOT EXISTS public.variant_metafields (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id text NOT NULL REFERENCES public.product_variants(variant_id) ON DELETE CASCADE,
  namespace_key text NOT NULL,
  metafield_type text,
  value text
);

-- Ensure total_inventory_qty is bigint if table previously existed as integer
ALTER TABLE public.products ALTER COLUMN total_inventory_qty TYPE bigint;

-- 2. Populate Production Catalog from Staging in an Atomic Transaction
BEGIN;

TRUNCATE TABLE 
  public.collection_metafields, 
  public.collection_conditions, 
  public.product_collections, 
  public.product_option_values, 
  public.product_options, 
  public.product_images, 
  public.product_variants, 
  public.products, 
  public.collections 
CASCADE;

INSERT INTO public.collections SELECT * FROM public.staging_collections;
INSERT INTO public.products SELECT * FROM public.staging_products;
INSERT INTO public.product_variants SELECT * FROM public.staging_product_variants;
INSERT INTO public.product_images SELECT * FROM public.staging_product_images;
INSERT INTO public.product_options SELECT * FROM public.staging_product_options;
INSERT INTO public.product_option_values SELECT * FROM public.staging_product_option_values;
INSERT INTO public.product_collections SELECT * FROM public.staging_product_collections;
INSERT INTO public.collection_conditions SELECT * FROM public.staging_collection_conditions;
INSERT INTO public.collection_metafields SELECT * FROM public.staging_collection_metafields;

COMMIT;

-- 3. High-Performance Indexing
CREATE INDEX IF NOT EXISTS idx_prod_variants_product ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_prod_images_product ON public.product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_prod_pc_product ON public.product_collections(product_id);
CREATE INDEX IF NOT EXISTS idx_prod_pc_collection ON public.product_collections(collection_id);
CREATE INDEX IF NOT EXISTS idx_prod_products_handle ON public.products(handle);
CREATE INDEX IF NOT EXISTS idx_prod_collections_handle ON public.collections(handle);

-- 4. Enable Row Level Security & Public Read Access
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_option_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_conditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_metafields ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read on products" ON public.products;
CREATE POLICY "Allow public read on products" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_variants" ON public.product_variants;
CREATE POLICY "Allow public read on product_variants" ON public.product_variants FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_images" ON public.product_images;
CREATE POLICY "Allow public read on product_images" ON public.product_images FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_options" ON public.product_options;
CREATE POLICY "Allow public read on product_options" ON public.product_options FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_option_values" ON public.product_option_values;
CREATE POLICY "Allow public read on product_option_values" ON public.product_option_values FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on collections" ON public.collections;
CREATE POLICY "Allow public read on collections" ON public.collections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on product_collections" ON public.product_collections;
CREATE POLICY "Allow public read on product_collections" ON public.product_collections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on collection_conditions" ON public.collection_conditions;
CREATE POLICY "Allow public read on collection_conditions" ON public.collection_conditions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on collection_metafields" ON public.collection_metafields;
CREATE POLICY "Allow public read on collection_metafields" ON public.collection_metafields FOR SELECT USING (true);

GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated;

-- 5. Verification Query (Returns exact counts in Production)
SELECT 'products' AS table_name, count(*) AS row_count FROM public.products
UNION ALL
SELECT 'product_variants', count(*) FROM public.product_variants
UNION ALL
SELECT 'product_images', count(*) FROM public.product_images
UNION ALL
SELECT 'collections', count(*) FROM public.collections
UNION ALL
SELECT 'product_collections', count(*) FROM public.product_collections
UNION ALL
SELECT 'product_options', count(*) FROM public.product_options
UNION ALL
SELECT 'product_option_values', count(*) FROM public.product_option_values
UNION ALL
SELECT 'collection_conditions', count(*) FROM public.collection_conditions
UNION ALL
SELECT 'collection_metafields', count(*) FROM public.collection_metafields;
