-- ==============================================================================
-- PHASE 5: ALIGN STAGING SCHEMA WITH AUTHORITATIVE SUPABASE_SCHEMA.sql
-- Target Project: https://grwhdtvorhdvyvcxwomn.supabase.co (grwhdtvorhdvyvcxwomn)
-- Tables: public.staging_* (Isolated staging environment)
--
-- Safety Guarantees:
-- - DROPS ONLY the old empty staging tables (already zeroed in Phase 4)
-- - DOES NOT touch auth.users, profiles, orders, commissions, reviews, etc.
-- - DOES NOT touch production catalog tables (products, collections)
-- ==============================================================================

-- 1. DROP OLD EMPTY STAGING TABLES
DROP TABLE IF EXISTS public.staging_collection_publications CASCADE;
DROP TABLE IF EXISTS public.staging_variant_metafields CASCADE;
DROP TABLE IF EXISTS public.staging_product_metafields CASCADE;
DROP TABLE IF EXISTS public.staging_collection_metafields CASCADE;
DROP TABLE IF EXISTS public.staging_collection_conditions CASCADE;
DROP TABLE IF EXISTS public.staging_product_collections CASCADE;
DROP TABLE IF EXISTS public.staging_product_images CASCADE;
DROP TABLE IF EXISTS public.staging_product_option_values CASCADE;
DROP TABLE IF EXISTS public.staging_product_options CASCADE;
DROP TABLE IF EXISTS public.staging_product_variants CASCADE;
DROP TABLE IF EXISTS public.staging_collections CASCADE;
DROP TABLE IF EXISTS public.staging_products CASCADE;

-- 2. CREATE ALIGNED STAGING PRODUCTS
CREATE TABLE public.staging_products (
  product_id text primary key,
  handle text unique not null,
  title text not null,
  body_html text,
  vendor text,
  product_type text,
  tags text,
  created_at timestamptz,
  updated_at timestamptz,
  status text,
  published boolean,
  published_at timestamptz,
  template_suffix text,
  gift_card boolean,
  source_url text,
  total_inventory_qty bigint,
  category_id text,
  category_name text,
  seo_title text,
  seo_description text
);

-- 3. CREATE ALIGNED STAGING COLLECTIONS
CREATE TABLE public.staging_collections (
  collection_id text primary key,
  handle text unique not null,
  title text not null,
  body_html text,
  sort_order text,
  template_suffix text,
  updated_at timestamptz,
  image_url text,
  products_count integer,
  published_online_store boolean,
  source_type text,
  inclusion_type text,
  inclusion_match text,
  seo_title text,
  seo_description text,
  smartseo_meta_title text,
  smartseo_meta_description text,
  smartseo_meta_keywords text
);

-- 4. CREATE ALIGNED STAGING PRODUCT OPTIONS
CREATE TABLE public.staging_product_options (
  option_key text primary key,
  product_id text not null references public.staging_products(product_id) on delete cascade,
  position integer not null,
  source_name text not null
);

-- 5. CREATE ALIGNED STAGING PRODUCT OPTION VALUES
CREATE TABLE public.staging_product_option_values (
  id bigint generated by default as identity primary key,
  option_key text not null references public.staging_product_options(option_key) on delete cascade,
  product_id text not null references public.staging_products(product_id) on delete cascade,
  value text not null
);

-- 6. CREATE ALIGNED STAGING PRODUCT VARIANTS
CREATE TABLE public.staging_product_variants (
  variant_id text primary key,
  product_id text not null references public.staging_products(product_id) on delete cascade,
  position integer,
  sku text,
  barcode text,
  option1_name text,
  option1_value text,
  option2_name text,
  option2_value text,
  option3_name text,
  option3_value text,
  image_url text,
  weight numeric,
  weight_unit text,
  price numeric,
  compare_at_price numeric,
  taxable boolean,
  inventory_item_id text,
  inventory_tracker text,
  inventory_policy text,
  fulfillment_service text,
  requires_shipping boolean,
  shipping_profile text,
  inventory_qty bigint,
  cost numeric,
  hs_code text,
  country_of_origin text,
  province_of_origin text
);

-- 7. CREATE ALIGNED STAGING PRODUCT IMAGES
CREATE TABLE public.staging_product_images (
  id bigint generated by default as identity primary key,
  product_id text not null references public.staging_products(product_id) on delete cascade,
  image_url text not null,
  image_type text,
  position integer,
  width integer,
  height integer,
  alt_text text
);

-- 8. CREATE ALIGNED STAGING PRODUCT COLLECTIONS
CREATE TABLE public.staging_product_collections (
  collection_id text not null references public.staging_collections(collection_id) on delete cascade,
  product_id text not null references public.staging_products(product_id) on delete cascade,
  collection_handle text,
  product_handle text,
  sort_position integer,
  source_verified text,
  primary key (collection_id, product_id)
);

-- 9. CREATE ALIGNED STAGING COLLECTION CONDITIONS
CREATE TABLE public.staging_collection_conditions (
  id bigint generated by default as identity primary key,
  collection_id text not null references public.staging_collections(collection_id) on delete cascade,
  condition_no integer,
  field text,
  relation text,
  value text,
  match text
);

-- 10. CREATE ALIGNED STAGING COLLECTION METAFIELDS
CREATE TABLE public.staging_collection_metafields (
  id bigint generated by default as identity primary key,
  collection_id text not null references public.staging_collections(collection_id) on delete cascade,
  namespace_key text not null,
  metafield_type text,
  value text
);

-- 11. CREATE ALIGNED STAGING PRODUCT METAFIELDS
CREATE TABLE public.staging_product_metafields (
  id bigint generated by default as identity primary key,
  product_id text not null references public.staging_products(product_id) on delete cascade,
  namespace_key text not null,
  metafield_type text,
  value text
);

-- 12. CREATE ALIGNED STAGING VARIANT METAFIELDS
CREATE TABLE public.staging_variant_metafields (
  id bigint generated by default as identity primary key,
  variant_id text not null references public.staging_product_variants(variant_id) on delete cascade,
  namespace_key text not null,
  metafield_type text,
  value text
);

-- 13. GRANT PERMISSIONS FOR POSTGREST ACCESS
GRANT ALL ON TABLE public.staging_products TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.staging_collections TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.staging_product_options TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.staging_product_option_values TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.staging_product_variants TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.staging_product_images TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.staging_product_collections TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.staging_collection_conditions TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.staging_collection_metafields TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.staging_product_metafields TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.staging_variant_metafields TO anon, authenticated, service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 14. RELOAD POSTGREST SCHEMA CACHE IMMEDIATELY
NOTIFY pgrst, 'reload schema';

